-- MySQL Script generated by MySQL Workbench
-- 11/17/15 21:44:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema treasure-thess
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `treasure-thess` ;

-- -----------------------------------------------------
-- Schema treasure-thess
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `treasure-thess` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `treasure-thess` ;

-- -----------------------------------------------------
-- Table `treasure-thess`.`AccessLevels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`AccessLevels` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`AccessLevels` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Auto increment access level id',
  `name` VARCHAR(45) NOT NULL COMMENT 'Access level name',
  `updated` TIMESTAMP NOT NULL COMMENT 'Access level updated time.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`Users` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`Users` (
  `id` INT NOT NULL COMMENT 'Auto increment user id',
  `username` VARCHAR(45) NOT NULL COMMENT 'User id given from the user. Used for the login system.',
  `password` VARCHAR(45) NOT NULL COMMENT 'User password.Used for the login system.',
  `access` INT NOT NULL COMMENT 'Access level id (Access:id)',
  `email` VARCHAR(45) NOT NULL COMMENT 'User email address',
  `ip` VARCHAR(45) NOT NULL COMMENT 'User global ip',
  `name` VARCHAR(45) NOT NULL COMMENT 'The real name from a user',
  `surname` VARCHAR(45) NOT NULL COMMENT 'The real surname from a user',
  `country` VARCHAR(45) NULL COMMENT 'Country name where the user lives.Can be null',
  `city` VARCHAR(45) NULL COMMENT 'City name where the user lives.Can be null',
  `address` VARCHAR(45) NULL COMMENT 'Home address from a user.Can be null',
  `phone` VARCHAR(45) NULL COMMENT 'The phone number from a user.Can be null',
  `last_login` TIMESTAMP NOT NULL COMMENT 'Last login date from the user.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  INDEX `alvl_idx` (`access` ASC)  COMMENT '',
  CONSTRAINT `access_level_id`
    FOREIGN KEY (`access`)
    REFERENCES `treasure-thess`.`AccessLevels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`Questionaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`Questionaires` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`Questionaires` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Auto increment questionaire id',
  `creatorid` INT NULL COMMENT 'Author id(Users:id)',
  `name` VARCHAR(45) NOT NULL COMMENT 'Questionaire name',
  `description` VARCHAR(45) NOT NULL COMMENT 'Questionaire description',
  `language` VARCHAR(45) NOT NULL COMMENT 'Questionaire language',
  `accepted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'If questionaire accepted from one admin',
  `updated` TIMESTAMP NOT NULL COMMENT 'Questionaire last updated time.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid_idx` (`creatorid` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  CONSTRAINT `questionaire_creator_user_id`
    FOREIGN KEY (`creatorid`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`QuestionGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`QuestionGroups` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`QuestionGroups` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Auto increment category id',
  `creator` INT NULL COMMENT '',
  `qid` INT NOT NULL COMMENT 'Quastionaires id (Quastionaires:id)',
  `name` VARCHAR(45) NOT NULL COMMENT 'Category name',
  `description` VARCHAR(45) NULL COMMENT 'Category description text. Can be null',
  `locationX` VARCHAR(255) NOT NULL COMMENT '',
  `locationY` VARCHAR(255) NOT NULL COMMENT '',
  `updated` TIMESTAMP NOT NULL COMMENT 'Category last updated time.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `qid_idx` (`qid` ASC)  COMMENT '',
  INDEX `questionGroup_creator_idx` (`creator` ASC)  COMMENT '',
  CONSTRAINT `questionGroup_questionaire_id`
    FOREIGN KEY (`qid`)
    REFERENCES `treasure-thess`.`Questionaires` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `questionGroup_creator`
    FOREIGN KEY (`creator`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`Questions` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`Questions` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'Auto increment question id',
  `qid` INT NULL COMMENT 'Questionaires id (Questionaires:id)',
  `uid` INT NULL COMMENT '',
  `gid` INT NOT NULL COMMENT 'QuestionGroups id (QuestionGroups:id)',
  `question` TEXT NOT NULL COMMENT 'Question name',
  `accepted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'If this question accepted from one admin',
  `updated` TIMESTAMP NOT NULL COMMENT 'Question last updated time.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `cid_idx` (`gid` ASC)  COMMENT '',
  INDEX `questionaire_id_idx` (`qid` ASC)  COMMENT '',
  INDEX `uid_idx` (`uid` ASC)  COMMENT '',
  UNIQUE INDEX `question_UNIQUE` (`question` ASC)  COMMENT '',
  CONSTRAINT `QuestionGroup_id_for_this_question`
    FOREIGN KEY (`gid`)
    REFERENCES `treasure-thess`.`QuestionGroups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Questionaire_id_for_this_question`
    FOREIGN KEY (`qid`)
    REFERENCES `treasure-thess`.`Questionaires` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `user_update_last_time_this_QuestionGroup`
    FOREIGN KEY (`uid`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`Answers` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`Answers` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Auto increment id',
  `uid` INT NULL COMMENT 'user who update last time this answer',
  `quid` INT NOT NULL COMMENT 'Question id (Questions:id)',
  `answer` VARCHAR(45) NOT NULL COMMENT 'Answer name',
  `description` VARCHAR(45) NULL COMMENT 'Answer description',
  `isCorrect` TINYINT(1) NOT NULL COMMENT 'if this answer is the correct for the question id',
  `updated` TIMESTAMP NOT NULL COMMENT 'when answer created',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `qid_idx` (`quid` ASC)  COMMENT '',
  INDEX `user_updated_last_time_this_answer_idx` (`uid` ASC)  COMMENT '',
  CONSTRAINT `question_for_this_answer`
    FOREIGN KEY (`quid`)
    REFERENCES `treasure-thess`.`Questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_who_update_last_time_this_answer`
    FOREIGN KEY (`uid`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`UserAnswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`UserAnswers` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`UserAnswers` (
  `uid` INT NULL COMMENT 'User id (Users:id)',
  `qid` INT NOT NULL COMMENT 'Question id (Questions:id)',
  `aid` INT NOT NULL COMMENT 'Answer id (Answers:id)',
  `locationX` VARCHAR(255) NOT NULL COMMENT '',
  `locationY` VARCHAR(255) NOT NULL COMMENT '',
  `anwered` TIMESTAMP NOT NULL COMMENT 'When the question answered',
  INDEX `uid_idx` (`uid` ASC)  COMMENT '',
  INDEX `qid_idx` (`qid` ASC)  COMMENT '',
  INDEX `aid_idx` (`aid` ASC)  COMMENT '',
  CONSTRAINT `User_who_answer_this_question`
    FOREIGN KEY (`uid`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `question_answered`
    FOREIGN KEY (`qid`)
    REFERENCES `treasure-thess`.`Questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `answer_which_answered`
    FOREIGN KEY (`aid`)
    REFERENCES `treasure-thess`.`Answers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`UserReports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`UserReports` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`UserReports` (
  `uid` INT NULL COMMENT 'user id (Users:id)',
  `quid` INT NOT NULL COMMENT 'Questionaires id (Questionaires:id)',
  `comment` VARCHAR(45) NOT NULL COMMENT 'Report comment from a user for a question id',
  `report_date` TIMESTAMP NOT NULL COMMENT '',
  INDEX `uid_idx` (`uid` ASC)  COMMENT '',
  INDEX `qid_idx` (`quid` ASC)  COMMENT '',
  CONSTRAINT `user_who_send_the_report`
    FOREIGN KEY (`uid`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `questionaire_reported`
    FOREIGN KEY (`quid`)
    REFERENCES `treasure-thess`.`Questionaires` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`Participations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`Participations` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`Participations` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Auto increment question id',
  `uid` INT NOT NULL COMMENT 'Users id (Users:id)',
  `qid` INT NOT NULL COMMENT 'Questionaires id (Questionaires:id)',
  `comment` VARCHAR(255) NULL COMMENT 'User partitipation comment to administrators.',
  `accepted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `partitipation_time` TIMESTAMP NOT NULL COMMENT 'User partitipation time.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `qid_idx` (`qid` ASC)  COMMENT '',
  INDEX `uid_idx` (`uid` ASC)  COMMENT '',
  CONSTRAINT `questionaire_partitipations`
    FOREIGN KEY (`qid`)
    REFERENCES `treasure-thess`.`Questionaires` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `participant_user`
    FOREIGN KEY (`uid`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treasure-thess`.`have_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treasure-thess`.`have_access` ;

CREATE TABLE IF NOT EXISTS `treasure-thess`.`have_access` (
  `id` INT NOT NULL COMMENT '',
  `uid` INT NOT NULL COMMENT '',
  `qid` INT NOT NULL COMMENT '',
  `accepted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `request_time` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `uid_idx` (`uid` ASC)  COMMENT '',
  INDEX `qid_idx` (`qid` ASC)  COMMENT '',
  CONSTRAINT `user_access_request`
    FOREIGN KEY (`uid`)
    REFERENCES `treasure-thess`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `questionaire_id_for_access`
    FOREIGN KEY (`qid`)
    REFERENCES `treasure-thess`.`Questionaires` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
